export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES";
export const FETCH_TRENDING_NOW = "FETCH_TRENDING_NOW";
export const FETCH_UPCOMING_MOVIES = "FETCH_UPCOMING_MOVIES";
export const FETCH_POPULAR_TV_SHOWS = "FETCH_POPULAR_TV_SHOWS";